apiVersion: v1

kind: Service
metadata:
  name: goserver
spec:
  selector:
    app: goserver

  type: LoadBalancer # This will create a service that is accessible from outside the cluster

  ports:
  - name: goserver-service
    port: 80 # This is the port that the service will listen on
    targetPort: 80 # This is the port that the container is listening on
    protocol: TCP

